#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 4 || ($1 != prepare && $1 != cleanup) ]]; then
  printf 'usage: %s prepare|cleanup <goos> <goarch> <staging-root>\n' "$0" >&2
  exit 2
fi
action=$1
goos=$2
goarch=$3
staging_root=$4
case ${goos}/${goarch} in
  darwin/amd64|darwin/arm64|linux/amd64|linux/arm64) ;;
  *) printf 'unsupported companion target: %s/%s\n' "${goos}" "${goarch}" >&2; exit 2 ;;
esac
repo=$(cd "$(dirname "$0")/.." && pwd -P)
if [[ ${staging_root} != /* ]]; then
  staging_root=${repo}/${staging_root}
fi
expected_root=${repo}/.goreleaser-companion
[[ ${staging_root} == "${expected_root}" ]] || { printf 'companion staging root must be %s\n' "${expected_root}" >&2; exit 2; }
stage=${staging_root}/${goos}_${goarch}
if [[ ${action} == cleanup ]]; then
  [[ -e ${staging_root} || -L ${staging_root} ]] || exit 0
  if [[ -L ${staging_root} || ! -d ${staging_root} || ! -O ${staging_root} ]]; then
    printf 'refuse unsafe companion cleanup root: %s\n' "${staging_root}" >&2
    exit 1
  fi
  resolved_root=$(cd "${staging_root}" && pwd -P)
  [[ ${resolved_root} == "${expected_root}" ]] || { printf 'refuse external companion cleanup root: %s\n' "${resolved_root}" >&2; exit 1; }
  if [[ -e ${stage} || -L ${stage} ]]; then
    if [[ -L ${stage} || ! -d ${stage} || ! -O ${stage} ]]; then
      printf 'refuse unsafe companion cleanup stage: %s\n' "${stage}" >&2
      exit 1
    fi
    resolved_stage=$(cd "${stage}" && pwd -P)
    [[ ${resolved_stage} == "${expected_root}/${goos}_${goarch}" ]] || { printf 'refuse external companion cleanup stage: %s\n' "${resolved_stage}" >&2; exit 1; }
    rm -rf -- "${resolved_stage}"
  fi
  rmdir "${resolved_root}" 2>/dev/null || true
  exit 0
fi
for tool in go jq; do
  command -v "${tool}" >/dev/null || { printf 'required companion tool is missing: %s\n' "${tool}" >&2; exit 3; }
done
if [[ -L ${staging_root} || (-e ${staging_root} && ! -d ${staging_root}) ]]; then
  printf 'companion staging root is unsafe: %s\n' "${staging_root}" >&2
  exit 7
fi
if [[ ! -e ${staging_root} ]]; then
  mkdir -m 0700 "${staging_root}"
fi
resolved_root=$(cd "${staging_root}" && pwd -P)
[[ ${resolved_root} == "${expected_root}" && -O ${resolved_root} ]] || { printf 'companion staging root is not the owned repository path: %s\n' "${resolved_root}" >&2; exit 7; }
if [[ -e ${stage} || -L ${stage} ]]; then
  printf 'refuse existing companion target stage: %s\n' "${stage}" >&2
  exit 7
fi
mkdir -m 0700 "${stage}"
resolved_stage=$(cd "${stage}" && pwd -P)
[[ ${resolved_stage} == "${expected_root}/${goos}_${goarch}" && -O ${resolved_stage} ]] || { printf 'companion target stage is unsafe: %s\n' "${resolved_stage}" >&2; exit 7; }
stage=${resolved_stage}

helper=${stage}/farrow-hosts-helper
(
  cd "${repo}"
  CGO_ENABLED=0 GOOS=${goos} GOARCH=${goarch} GOFLAGS=-mod=readonly \
    go build -trimpath -buildvcs=false -ldflags '-buildid= -s -w' \
      -o "${helper}" ./cmd/farrow-hosts-helper
)
if command -v sha256sum >/dev/null 2>&1; then
  helper_sha=$(sha256sum "${helper}" | awk '{print $1}')
else
  helper_sha=$(shasum -a 256 "${helper}" | awk '{print $1}')
fi
[[ ${helper_sha} =~ ^[0-9a-f]{64}$ ]] || { printf 'invalid companion digest\n' >&2; exit 1; }

generated=${stage}/companion_digest_release.go
{
  printf '// Code generated by packaging/goreleaser-companion.sh; DO NOT EDIT.\n'
  printf 'package hostconfig\n\n'
  printf 'func init() { ExpectedHelperSHA256 = "%s" }\n' "${helper_sha}"
} >"${generated}"
chmod 0600 "${generated}"

virtual=${repo}/internal/hostconfig/companion_digest_release_generated.go
jq -n --arg virtual "${virtual}" --arg generated "${generated}" \
  '{Replace: {($virtual): $generated}}' >"${stage}/overlay.json"
chmod 0600 "${stage}/overlay.json"
printf 'prepared paired helper digest for %s/%s: %s\n' "${goos}" "${goarch}" "${helper_sha}"
