#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 4 || ($1 != prepare && $1 != cleanup) ]]; then
  printf 'usage: %s prepare|cleanup <goos> <goarch> <staging-root>\n' "$0" >&2
  exit 2
fi
action=$1
goos=$2
goarch=$3
staging_root=$4
case ${goos}/${goarch} in
  darwin/amd64|darwin/arm64|linux/amd64|linux/arm64) ;;
  *) printf 'unsupported companion target: %s/%s\n' "${goos}" "${goarch}" >&2; exit 2 ;;
esac
repo=$(cd "$(dirname "$0")/.." && pwd -P)
if [[ ${staging_root} != /* ]]; then
  staging_root=${repo}/${staging_root}
fi
[[ ${staging_root} != / && ${staging_root} != "${repo}" ]] || { printf 'unsafe companion staging root: %s\n' "${staging_root}" >&2; exit 2; }
install -d -m 0755 "${staging_root}"
staging_root=$(cd "${staging_root}" && pwd -P)
stage=${staging_root}/${goos}_${goarch}
if [[ ${action} == cleanup ]]; then
  case ${stage} in
    "${staging_root}"/darwin_amd64|"${staging_root}"/darwin_arm64|"${staging_root}"/linux_amd64|"${staging_root}"/linux_arm64)
      rm -rf -- "${stage}"
      rmdir "${staging_root}" 2>/dev/null || true
      exit 0
      ;;
    *) printf 'refuse unsafe companion cleanup: %s\n' "${stage}" >&2; exit 1 ;;
  esac
fi
for tool in go jq; do
  command -v "${tool}" >/dev/null || { printf 'required companion tool is missing: %s\n' "${tool}" >&2; exit 3; }
done
install -d -m 0700 "${stage}"

helper=${stage}/piglet-hosts-helper
(
  cd "${repo}"
  CGO_ENABLED=0 GOOS=${goos} GOARCH=${goarch} GOFLAGS=-mod=readonly \
    go build -trimpath -buildvcs=false -ldflags '-buildid= -s -w' \
      -o "${helper}" ./cmd/piglet-hosts-helper
)
if command -v sha256sum >/dev/null 2>&1; then
  helper_sha=$(sha256sum "${helper}" | awk '{print $1}')
else
  helper_sha=$(shasum -a 256 "${helper}" | awk '{print $1}')
fi
[[ ${helper_sha} =~ ^[0-9a-f]{64}$ ]] || { printf 'invalid companion digest\n' >&2; exit 1; }

generated=${stage}/companion_digest_release.go
{
  printf '// Code generated by packaging/goreleaser-companion.sh; DO NOT EDIT.\n'
  printf 'package hostconfig\n\n'
  printf 'func init() { ExpectedHelperSHA256 = "%s" }\n' "${helper_sha}"
} >"${generated}"
chmod 0600 "${generated}"

virtual=${repo}/internal/hostconfig/companion_digest_release_generated.go
jq -n --arg virtual "${virtual}" --arg generated "${generated}" \
  '{Replace: {($virtual): $generated}}' >"${stage}/overlay.json"
chmod 0600 "${stage}/overlay.json"
printf 'prepared paired helper digest for %s/%s: %s\n' "${goos}" "${goarch}" "${helper_sha}"
